// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3eNmYfGNL49rEmnoPD8Rlyuc7DNJMw24',
    appId: '1:935058642294:web:cdd1e810047cf25ead1657',
    messagingSenderId: '935058642294',
    projectId: 'spotku',
    authDomain: 'spotku.firebaseapp.com',
    storageBucket: 'spotku.firebasestorage.app',
    measurementId: 'G-NBC908CV63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYk-7O0Sf2DU-uTmaUcnarYY71XpDKId4',
    appId: '1:935058642294:android:3d2ed5acd013fa83ad1657',
    messagingSenderId: '935058642294',
    projectId: 'spotku',
    storageBucket: 'spotku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUuKy9OJou-1Aw9uyUi2-X5WteUl056BQ',
    appId: '1:935058642294:ios:cc4199074a5f0d36ad1657',
    messagingSenderId: '935058642294',
    projectId: 'spotku',
    storageBucket: 'spotku.firebasestorage.app',
    iosClientId:
        '935058642294-62v62usqiecjsa9t9fl37jekiuahqsrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUuKy9OJou-1Aw9uyUi2-X5WteUl056BQ',
    appId: '1:935058642294:ios:cc4199074a5f0d36ad1657',
    messagingSenderId: '935058642294',
    projectId: 'spotku',
    storageBucket: 'spotku.firebasestorage.app',
    iosClientId:
        '935058642294-62v62usqiecjsa9t9fl37jekiuahqsrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3eNmYfGNL49rEmnoPD8Rlyuc7DNJMw24',
    appId: '1:935058642294:web:373a27e7e75e6af1ad1657',
    messagingSenderId: '935058642294',
    projectId: 'spotku',
    authDomain: 'spotku.firebaseapp.com',
    storageBucket: 'spotku.firebasestorage.app',
    measurementId: 'G-DXB03X7960',
  );
}
